frame_id: shelf_base
boxes:
  # bin A
  - position: [0, 0.325, 0.1] 
    dimension: [0.5, 0.3, 0.2]
  # bin B
  - position: [0, 0, 0.1]
    dimension: [0.5, 0.35, 0.2] 
  # bin C
  - position: [0, -0.325, 0.1]
    dimension: [0.5, 0.3, 0.2] 
