vacuum_gripper:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - right_gripper_prismatic_joint
    - right_gripper_vacuum_pad_joint
hand:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - right_gripper_finger_yaw_joint
    - right_gripper_finger_roll_joint
