id: 131073
command: 'configure'
args: '{ "urdf":{ "name": "left_gripper_mass", "link": [ { "name": "left_gripper_mass", "inertial": { "mass": { "value": 1.18 }, "origin": { "xyz": [0.0, 0.0, 0.15] } } } ] }}'
