<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="right_vacuum_gripper">
  <xacro:include filename="$(find jsk_2016_01_baxter_apc)/robots/common_constants.xacro"/>
  <!-- Gazebo Tags -->
  <gazebo reference="right_gripper_base">
    <selfCollide>true</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="right_gripper_tube">
    <selfCollide>true</selfCollide>
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="right_gripper_pad_with_base">
    <selfCollide>true</selfCollide>
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="right_gripper_l_finger_base">
    <selfCollide>true</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="right_gripper_r_finger_base">
    <selfCollide>true</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="right_gripper_l_finger">
    <selfCollide>true</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="right_gripper_r_finger">
    <selfCollide>true</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="right_gripper_vacuum_pad_joint">
    <implicitSpringDamper>false</implicitSpringDamper>
  </gazebo>
  <gazebo reference="right_gripper_prismatic_joint">
    <implicitSpringDamper>false</implicitSpringDamper>
  </gazebo>
  <!--Link bodies-->
  <xacro:property name="base_rect_offset_x" value="0.0065" />
  <xacro:property name="base_rect_l" value="0.2805" />
  <xacro:property name="base_rect_h" value="0.107" />
  <xacro:property name="base_rect_w" value="0.15" />
  <xacro:property name="camera_rect_offset_x" value="-0.061" />
  <xacro:property name="camera_rect_offset_y" value="-0.037" />
  <xacro:property name="camera_rect_offset_z" value="0.004" />
  <xacro:property name="camera_rect_l" value="0.04" />
  <xacro:property name="camera_rect_h" value="0.03" />
  <xacro:property name="camera_rect_w" value="0.165" />
  <xacro:property name="tube_rect_offset_x" value="0.0475" />
  <xacro:property name="tube_rect_offset_y" value="0.012" />
  <xacro:property name="tube_rect_offset_z" value="0.17" />
  <xacro:property name="tube_rect_l" value="0.29" />
  <xacro:property name="tube_rect_h" value="0.034" />
  <xacro:property name="tube_rect_w" value="0.081" />
  <xacro:property name="pad_with_base_offset_x" value="-0.048" />
  <xacro:property name="pad_with_base_offset_y" value="-0.0005" />
  <xacro:property name="pad_with_base_offset_z" value="-0.302" />
  <xacro:property name="pad_with_base_col_z" value="0.0145" />
  <xacro:property name="pad_with_base_rect_l" value="0.055" />
  <xacro:property name="pad_with_base_rect_h" value="0.028" />
  <xacro:property name="pad_with_base_rect_w" value="0.028" />
  <xacro:property name="finger_base_rect_l" value="0.022" />
  <xacro:property name="finger_base_rect_h" value="0.032" />
  <xacro:property name="finger_base_rect_w" value="0.036" />
  <xacro:property name="finger_rect_l" value="0.04" />
  <xacro:property name="finger_rect_h" value="0.016" />
  <xacro:property name="finger_rect_w" value="0.11" />
  <!--Joints-->
  <xacro:property name="hand_offset_x" value="-0.01" />
  <xacro:property name="hand_offset_z" value="0" />
  <xacro:property name="pad_joint_offset_x" value="0.048" />
  <xacro:property name="pad_joint_offset_y" value="0.0005" />
  <xacro:property name="pad_joint_offset_z" value="0.302" />
  <xacro:property name="finger_base_offset_z" value="0.291352" />
  <xacro:property name="finger_base_offset_x" value="-0.014" />
  <xacro:property name="l_finger_base_offset_y" value="0.026" />
  <xacro:property name="r_finger_base_offset_y" value="-0.026" />
  <xacro:property name="palm_offset_x" value="0.015" />
  <xacro:property name="palm_offset_z" value="0.28" />

  <!--Link bodies-->
  <link name="right_gripper_base">
    <visual>
      <origin rpy="${M_PI/2} 0 ${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/right_gripper_base_main.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lightgrey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <visual>
      <origin rpy="${M_PI/2} 0 ${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/right_gripper_palm_pad.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lightbrown">
        <color rgba="0.6 0.5 0.2 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="${base_rect_offset_x} 0 ${base_rect_l/2}"/>
      <geometry>
        <box size="${base_rect_h} ${base_rect_w} ${base_rect_l}"/>
      </geometry>
    </collision>
    <collision>
      <origin rpy="0 0 0" xyz="${camera_rect_offset_x} ${camera_rect_offset_y} ${camera_rect_offset_z}"/>
      <geometry>
        <box size="${camera_rect_h} ${camera_rect_w} ${camera_rect_l}"/>
      </geometry>
    </collision>
    <!--FIXME: Adjust inertia-->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.3"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  <link name="right_gripper_tube">
    <visual>
      <origin rpy="${M_PI/2} 0 ${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/right_gripper_tube_connectors.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lightgrey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <visual>
      <origin rpy="${M_PI/2} 0 ${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/right_gripper_tube_main.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white">
        <color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <visual>
      <origin rpy="${M_PI/2} 0 ${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/right_gripper_tube_gear.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0.24 0.82 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="${tube_rect_offset_x} ${tube_rect_offset_y} ${tube_rect_offset_z}"/>
      <geometry>
        <box size="${tube_rect_h} ${tube_rect_w} ${tube_rect_l}"/>
      </geometry>
    </collision>
    <!--FIXME: Adjust inertia-->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.3"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  <link name="right_gripper_pad_with_base">
    <visual>
      <origin rpy="${M_PI/2} 0 ${M_PI/2}" xyz="${pad_with_base_offset_x} ${pad_with_base_offset_y} ${pad_with_base_offset_z}"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/right_gripper_vacuum_pad_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lightgrey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <visual>
      <origin rpy="${M_PI/2} 0 ${M_PI/2}" xyz="${pad_with_base_offset_x} ${pad_with_base_offset_y} ${pad_with_base_offset_z}"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/right_gripper_vacuum_pad.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${pad_with_base_col_z}"/>
      <geometry>
        <box size="${pad_with_base_rect_h} ${pad_with_base_rect_w} ${pad_with_base_rect_l}"/>
      </geometry>
    </collision>
    <!--FIXME: Adjust inertia-->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  <link name="right_gripper_r_finger_base">
    <visual>
      <origin rpy="${M_PI/2} 0 ${M_PI}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/finger_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lightgrey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${-finger_base_rect_l/2}"/>
      <geometry>
        <box size="${finger_base_rect_h} ${finger_base_rect_w} ${finger_base_rect_l}"/>
      </geometry>
    </collision>
    <!--FIXME: Adjust inertia-->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  <link name="right_gripper_l_finger_base">
    <visual>
      <origin rpy="${M_PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/finger_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lightgrey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${-finger_base_rect_l/2}"/>
      <geometry>
        <box size="${finger_base_rect_h} ${finger_base_rect_w} ${finger_base_rect_l}"/>
      </geometry>
    </collision>
    <!--FIXME: Adjust inertia-->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  <link name="right_gripper_r_finger">
    <visual>
      <origin rpy="${M_PI/2} 0 ${M_PI}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/finger_main.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lightgrey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <visual>
      <origin rpy="${M_PI/2} 0 ${M_PI}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/finger_pad.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lightbrown">
        <color rgba="0.6 0.5 0.2 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 ${-finger_rect_w/2} 0"/>
      <geometry>
        <box size="${finger_rect_h} ${finger_rect_w} ${finger_rect_l}"/>
      </geometry>
    </collision>
    <!--FIXME: Adjust inertia-->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  <link name="right_gripper_l_finger">
    <visual>
      <origin rpy="${M_PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/finger_main.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lightgrey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <visual>
      <origin rpy="${M_PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/gripper-v5/visual/finger_pad.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lightbrown">
        <color rgba="0.6 0.5 0.2 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 ${finger_rect_w/2} 0"/>
      <geometry>
        <box size="${finger_rect_h} ${finger_rect_w} ${finger_rect_l}"/>
      </geometry>
    </collision>
    <!--FIXME: Adjust inertia-->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  <link name="right_gripper_palm_endpoint"/>

  <!--Joints-->
  <joint name="right_gripper_base_fixed" type="fixed">
    <origin rpy="0 0 0" xyz="${hand_offset_x} 0 ${hand_offset_z}" />
    <parent link="right_hand"/>
    <child link="right_gripper_base"/>
  </joint>
  <joint name="right_gripper_prismatic_joint" type="prismatic">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="right_gripper_base"/>
    <child link="right_gripper_tube"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="0.124" effort="0" velocity="0.132"/>
    <dynamics damping="0.7"/>
  </joint>
  <joint name="right_gripper_vacuum_pad_joint" type="revolute">
    <origin rpy="0 0 0" xyz="${pad_joint_offset_x} ${pad_joint_offset_y} ${pad_joint_offset_z}"/>
    <parent link="right_gripper_tube"/>
    <child link="right_gripper_pad_with_base"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.58" upper="1.58" effort="0" velocity="3.36"/>
    <dynamics damping="0.7"/>
  </joint>
  <joint name="right_gripper_finger_yaw_joint" type="revolute">
    <origin rpy="0 0 0" xyz="${finger_base_offset_x} ${l_finger_base_offset_y} ${finger_base_offset_z}"/>
    <parent link="right_gripper_base"/>
    <child link="right_gripper_l_finger_base"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="1.58" effort="0" velocity="4.23"/>
    <dynamics damping="0.7"/>
  </joint>
  <joint name="right_gripper_r_finger_yaw_joint" type="revolute">
    <origin rpy="0 0 0" xyz="${finger_base_offset_x} ${r_finger_base_offset_y} ${finger_base_offset_z}"/>
    <parent link="right_gripper_base"/>
    <child link="right_gripper_r_finger_base"/>
    <mimic joint="right_gripper_finger_yaw_joint" multiplier="1"/>
    <axis xyz="0 0 -1"/>
    <limit lower="0" upper="1.58" effort="0" velocity="4.23"/>
    <dynamics damping="0.7"/>
  </joint>
  <joint name="right_gripper_finger_roll_joint" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="right_gripper_l_finger_base"/>
    <child link="right_gripper_l_finger"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="3.14" effort="0" velocity="5.5"/>
    <dynamics damping="0.7"/>
  </joint>
  <joint name="right_gripper_r_finger_roll_joint" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="right_gripper_r_finger_base"/>
    <child link="right_gripper_r_finger"/>
    <mimic joint="right_gripper_finger_roll_joint" multiplier="1"/>
    <axis xyz="-1 0 0"/>
    <limit lower="0" upper="3.14" effort="0" velocity="5.5"/>
    <dynamics damping="0.7"/>
  </joint>
  <joint name="right_gripper_palm_endpoint_fixed" type="fixed">
    <origin rpy="0 ${M_PI} 0" xyz="${palm_offset_x} 0 ${palm_offset_z}" />
    <parent link="right_gripper_base"/>
    <child link="right_gripper_palm_endpoint"/>
  </joint>

  <!--Transmission-->
  <transmission name="right_gripper_prismatic_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_gripper_prismatic_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_gripper_prismatic_joint_motor">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>41.66666667</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="right_gripper_vacuum_pad_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_gripper_vacuum_pad_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_gripper_vacuum_pad_tendon_winder">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1.637369792</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="right_gripper_finger_yaw_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_gripper_finger_yaw_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_gripper_finger_yaw_joint_motor">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1.3</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="right_gripper_finger_roll_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_gripper_finger_roll_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_gripper_finger_tendon_winder">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1.0</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
